// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtXx5CdUKoZMYSMj-hqFrhhVG_LD__Zn4',
    appId: '1:942545478004:web:3dc4dac7249a2ab2090c21',
    messagingSenderId: '942545478004',
    projectId: 'vital-tech-bacbc',
    authDomain: 'vital-tech-bacbc.firebaseapp.com',
    databaseURL: 'https://vital-tech-bacbc-default-rtdb.firebaseio.com',
    storageBucket: 'vital-tech-bacbc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQlSXGarUhtj_dWrrUFXH4AxqWGWrbDQY',
    appId: '1:942545478004:android:526b48ef8d6051da090c21',
    messagingSenderId: '942545478004',
    projectId: 'vital-tech-bacbc',
    databaseURL: 'https://vital-tech-bacbc-default-rtdb.firebaseio.com',
    storageBucket: 'vital-tech-bacbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy__azM10iWl6xRRyQUtHah-Vnjkx2NuQ',
    appId: '1:942545478004:ios:267f1566bdc22021090c21',
    messagingSenderId: '942545478004',
    projectId: 'vital-tech-bacbc',
    databaseURL: 'https://vital-tech-bacbc-default-rtdb.firebaseio.com',
    storageBucket: 'vital-tech-bacbc.firebasestorage.app',
    iosBundleId: 'com.example.vital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy__azM10iWl6xRRyQUtHah-Vnjkx2NuQ',
    appId: '1:942545478004:ios:267f1566bdc22021090c21',
    messagingSenderId: '942545478004',
    projectId: 'vital-tech-bacbc',
    databaseURL: 'https://vital-tech-bacbc-default-rtdb.firebaseio.com',
    storageBucket: 'vital-tech-bacbc.firebasestorage.app',
    iosBundleId: 'com.example.vital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsQh55g9c81NkTunmRxCKPUgPyc0Rqs2Q',
    appId: '1:942545478004:web:6bb2023164ea8838090c21',
    messagingSenderId: '942545478004',
    projectId: 'vital-tech-bacbc',
    authDomain: 'vital-tech-bacbc.firebaseapp.com',
    databaseURL: 'https://vital-tech-bacbc-default-rtdb.firebaseio.com',
    storageBucket: 'vital-tech-bacbc.firebasestorage.app',
  );
}
